<?php
	#AUTOGENERATED BY HYBRIDAUTH 2.1.2 INSTALLER - Sunday 8th of June 2014 03:15:51 PM

/*!
* HybridAuth
* http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
* (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return 
	array(
		"base_url" => "http://www.lektroniq.ro/hybridauth/", 

		"providers" => array ( 
			// openid providers
			"OpenID" => array (
				"enabled" => false
			),

			"AOL"  => array ( 
				"enabled" => false 
			),

			"Yahoo" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "dj0yJmk9MnphbUtQQmJQazFsJmQ9WVdrOVZURnhhM0pTTjJzbWNHbzlNQS0tJnM9Y29uc3VtZXJzZWNyZXQmeD1lOQ--", "secret" => "687eab8c97719e95790ecac6219e732997b39ef3" )
			),

			"Google" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "301167409103-5o5av03s31lamjq45mlgk7bd7p111ue2.apps.googleusercontent.com", "secret" => "mzkC1KigOBumKdYULU335IWp" )
			),

			"Facebook" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "514100822052648", "secret" => "15a2c5c75d4b775b1629573420cf92e4" )
			),

			"Twitter" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "lT8CpACg7dyxfaMxZCpuz2kqB", "secret" => "tR2AqbI6GJP4fQCpl5Li2QdwEy1Yb10mvZgb1ecLC9fZTzWYlB" ) 
			),

			// windows live
			"Live" => array ( 
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),

			"MySpace" => array ( 
				"enabled" => false,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"LinkedIn" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "77ognnsi6jgx19", "secret" => "aqmkwCpXOHpSuhhx" ) 
			),

			"Foursquare" => array (
				"enabled" => false,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),
		),

		// if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
		"debug_mode" => false,

		"debug_file" => ""
	);
